// Error handling 

console.log("Welcome to tutorial 50");
try{

console.log("try block executed");
console.log(x);

console.log("try block ends here");
}
catch(e){
    console.log("catch block executed");
   
}